config/routes.rb
Jmo::Application.routes.draw do
  resources :voices

  devise_for :users
  root "voices#index"
  get "about" => "pages#about"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  #each user has many voices
  has_many :voices

end

app/models/voice.rb
class Voice < ActiveRecord::Base
	#opinion must not be blank
	validates :opinion, presence: true 
	validates :user_id, presence: true

	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/voices_controller.rb
class VoicesController < ApplicationController
  #before user can do anything to voices, must sign in, except seeing the voices (index page)
  before_filter :authenticate_user!, except: [:index]
  before_action :set_voice, only: [:show, :edit, :update, :destroy]

  # GET /voices
  # GET /voices.json
  def index
    @voices = Voice.order("created_at desc")
  end

  # GET /voices/1
  # GET /voices/1.json
  def show
  end

  # GET /voices/new
  def new
    #associate new voices with users
    @voice = current_user.voices.new
  end

  # GET /voices/1/edit
  def edit
    # makes sure no other user can mess with other uses voices
    @voice = current_user.voices.find(params[:id])
  end

  # POST /voices
  # POST /voices.json
  def create
    @voice = current_user.voices.new(voice_params)

    respond_to do |format|
      if @voice.save
        format.html { redirect_to @voice, notice: 'Voice was successfully created.' }
        format.json { render action: 'show', status: :created, location: @voice }
      else
        format.html { render action: 'new' }
        format.json { render json: @voice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voices/1
  # PATCH/PUT /voices/1.json
  def update
    #only user with the right ID can update
    @voice = current_user.voices.find(params[:id])

    respond_to do |format|
      if @voice.update(voice_params)
        format.html { redirect_to @voice, notice: 'Voice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @voice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voices/1
  # DELETE /voices/1.json
  def destroy
    #only users with the right ids can destroy
    @voice = current_user.voices.find(params[:id])
    @voice.destroy
    respond_to do |format|
      format.html { redirect_to voices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voice
      @voice = Voice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voice_params
      params.require(:voice).permit(:opinion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/voices_helper.rb
module VoicesHelper
end

app/views/layouts/_footer.html.erb
	<small>
		This Project is by <%= link_to "Chung", about_path%>
	</small>

app/views/layouts/_header.html.erb
<ul class = "nav nav-tabs">
	<li id = "nav-list" class = "logo"><%= link_to "JMO", root_path, class: "home" %></li>
		<% if user_signed_in? %>
			<li id = "nav-list" class = "pull-right"><%= link_to "Logout",  destroy_user_session_path, method: :delete %></li>
			<li id = "nav-list" class = "pull-right"><%= link_to "Edit",  edit_user_registration_path%></li>
			<li id = "new" class = "pull-right"><%= link_to 'New Opinion', new_voice_path %></li>
		<% else %>
			<li id = "nav-list" class = "pull-right"><%= link_to "Log In" , new_user_session_path %></li>
			<li id = "nav-list" class = "pull-right"><%= link_to "Sign Up" , new_user_registration_path%></li>
		<%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>JMO | Just My Opinion</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div id = "wrap">
			<div class = "container">
				<%= render "layouts/header" %>

				<% flash.each do |name, msg| %>
						<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
				<%end%>
				<div class = "row">
					<div class="col-lg-10 col-lg-offset-1">
						<div class="text-center">
							<%= yield %>
						</div>
					</div>
				</div>
				<div class = "push"></div>

				<div class = "footer">
					<%= render "layouts/footer" %>
				</div>
			</div>
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
	<h1 id = "welcome">Welcome Stranger,</h1>
	<h1 id = "welcome">To Simply An Opinion</h1>
	<p id = "home-p">Everyone's opinions matters, whether it's on politics, environments, friendship, or even something as mundane as what to eat for breakfast. While some opinions enlight, others enrage. Hopefully some of the opinions below will broaden your mind and challenge your beliefs. </p>
	<p id = "home-p">If you'd like, you may <%= link_to "click here", new_user_registration_path%> to sign up and begin to share your own opinions with the world.</p>

app/views/voices/_form.html.erb
<%= simple_form_for(@voice, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

	<div class="form-inputs">
    	<%= f.input :opinion, as: :text, input_html: {rows:"10"} %>
  	</div>
	</br>

  	<div class="form-actions">
    	<%= f.button :submit, class: "btn btn-danger" %>
  	</div>
	</br>
<% end %>

app/views/voices/_voice.html.erb
<tr class = "opinion-list">
  	<td id = "opinion"><%= voice.opinion %></td>
  	<div class = "crudlist">
	  	<td><%= link_to 'Show', voice, class: "crud" %></td>
	  	<%if current_user == voice.user %>
		  <td><%= link_to 'Edit', edit_voice_path(voice), class: "crud" %></td>
		  <td><%= link_to 'Destroy', voice, method: :delete, data: { confirm: 'Are you sure?' }, class: "crud" %></td>
		<%end %>
	</div>
</tr>

app/views/voices/edit.html.erb
<h1>Editing voice</h1>

<%= render 'form' %>

<%= link_to 'Show', @voice %> |
<%= link_to 'Back', voices_path %>

app/views/voices/index.html.erb
<%unless user_signed_in?%>
	<h1 id = "welcome">Welcome Stranger,</h1>
	<h1 id = "welcome">Ready To Voice Your Opinion?</h1>
	<p id = "home-p">Everyone's opinions matters, whether it's on politics, environments, friendship, or even something as mundane as what to eat for breakfast. While some opinions enlight, others enrage. Hopefully some of the opinions below will broaden your mind and challenge your beliefs. </p>
	<p id = "home-p">If you'd like, you may <%= link_to "click here", new_user_registration_path%> to sign up and begin to share your own opinions with the world.</p>
	</br>
<%end%>
	<h1 id = "current">Current Opinions</h1>
	</br>
	<table>
	  <tbody>
	    	<%= render @voices %>
	  </tbody>
	</table>

app/views/voices/new.html.erb
<h1>What Do You Want To Tell the World?</h1>
</br>
<p style = "color:red; font-size: 1.35em;">* Voice your opinion in a rational and logical manner.</p>
<p style = "color:red; font-size: 1.35em;">* Try not to include any curse words or swearing.</p>
<p style = "color:red; font-weight:bold; font-size: 1.35em;">* ALWAYS EXPLAIN THE "WHY" OF THE OPINION</p>
</br>
<%= render 'form' %>

<%= link_to 'Back', voices_path %>

app/views/voices/show.html.erb
<p id="notice"><%= notice %></p>

<div class = "well">
	<p>
	  <strong>Opinion:</strong>
	  <%= @voice.opinion %>
	  </br>
	  <div class = "timestamp">Created on <%= @voice.created_at.strftime("%b. %d, %Y")%> at <%= @voice.created_at.strftime("%H:%M")%> </div>
	</p>
	<% if current_user == @voice.user %>
		<%= link_to 'Edit', edit_voice_path(@voice) %> |
	<%end%>
	<%= link_to 'Back', voices_path %>
</div>